[tool.poetry]
name = "blockpipe"
version = "0.1.2"
description = ""
authors = ["Sorawit Suriyakarn <thepsint@gmail.com>"]
readme = "README.md"
packages = [{include = "blockpipe"}]

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.30.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
