[tool.poetry]
name = "seven_api_sdk"
version = "0.1.7"
description = "A package for end users to use the API endpoints of SEVEN with ease."
readme = "README.md"
authors = ["Daniel Molnar <daniel@prjct8.ch>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.26.24"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
