[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hex_utility_pkg"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version>"3.8"',
]

[tool.setuptools.packages.find]
# All the following settings are optional:
where = ["src"]  # ["."] by default
include = ["*pkg"]  # ["*"] by default
exclude = [".git",".venv","images","build_folder","my_python_lib","python_crash_course","UI"]  # empty by default
namespaces = false  # true by default


