[tool.poetry]
name = "fastapi-request-id"
version = "1.1.1"
description = ""
authors = ["Stanislav Tsoy <dev.stanislav@gmail.com>"]
readme = "README.md"
packages = [{include = "fastapi_request_id", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.95.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
httpx = "^0.23.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
