[tool.poetry]
name = "InternetArchiveSync"
version = "1.0.2"
description = "A python tool to donwload an internet archive."
authors = ["Mathieu <git@bigbisous.org>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
defusedxml = "^0.7.1"
rich = "^13.3.5"
pytest = "^7.3.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pytest = "^7.3.1"
pylint = "^2.17.4"
isort = "^5.12.0"
bandit = "^1.7.5"
flake8 = "^6.0.0"
mypy = "^1.3.0"
types-requests = "^2.27.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
async = "internetarchivesync.sync:main"

[tool.pylint.messages_control]
disable = "C0330, C0326"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.'MESSAGES CONTROL']
disable =  ["logging-fstring-interpolation"]

[tool.isort]
profile = "black"