[tool.poetry]
name = "AlekSIS-App-Untis"
version = "3.0"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"
include = [
    { path = "aleksis/**/*.mo", format = ["sdist", "wheel"] },
    { path = "*.rst", format = "sdist" },
    { path = "docs/*", format = "sdist" },
    { path = "docs/**/*", format = "sdist" },
    { path = "conftest.py", format = "sdist" },
    { path = "tox.ini", format = "sdist" }
]

description = "AlekSIS (School Information System) — App for Untis import"
authors = ["Dominik George <dominik.george@teckids.org>", "Julian Leucker <leuckeju@katharineum.de>", "Frank Poetzsch-Heffter <p-h@katharineum.de>", "Jonathan Weth <dev@jonathanweth.de>", "Tom Teichler <tom.teichler@teckids.org>", "mirabilos <thorsten.glaser@teckids.org>"]
maintainers = ["Jonathan Weth <dev@jonathanweth.de>", "Dominik George <dominik.george@teckids.org>"]
license = "EUPL-1.2-or-later"
homepage = "https://aleksis.org/"
repository = "https://edugit.org/AlekSIS/official/AlekSIS-App-Untis"
documentation = "https://aleksis.org/AlekSIS/docs/html/"
keywords = ["SIS", "education", "school", "timetable", "plans"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Django :: 3.0",
    "Intended Audience :: Education",
    "Topic :: Education",
    "Typing :: Typed",
]

[[tool.poetry.source]]
name = "gitlab"
url = "https://edugit.org/api/v4/projects/461/packages/pypi/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
mysqlclient = "^2.0.0"
tqdm = "^4.44.1"
defusedxml = "^0.7.0"
aleksis-core = "^3.0"
aleksis-app-chronos = "^3.0"

[tool.poetry.dev-dependencies]
aleksis-builddeps = "*"

[tool.poetry.plugins."aleksis.app"]
untis = "aleksis.apps.untis.apps:UntisConfig"

[tool.black]
line-length = 100
exclude = "/migrations/"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
