[tool.poetry]
name = "fiat-copilot"
version = "0.2.0"
description = "üßë‚ÄçüöÄ - Fiat Copilot is a variety of utilities to smooth your ML development workflow."
authors = ["ValerioL29 <cheng2029@foxmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "fiat_copilot"}]

[tool.poetry.dependencies]
python = "^3.10"
ray = {extras = ["default"], version = "^2.4.0"}
xgboost = "^1.7.5"
xgboost-ray = "^0.1.15"
dagster = "^1.3.4"
dagit = "^1.3.4"
oss2 = "^2.17.0"
esdk-obs-python = "^3.22.2"
cos-python-sdk-v5 = "^1.9.24"

[[tool.poetry.source]]
name = "mirrors"
url = "https://pypi.tuna.tsinghua.edu.cn/simple/"
default = true


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
