[tool.poetry]
name = "sync-list"
version = "1.0.0"
description = "SyncList - список Python с автоматической синхронизацией данных с файлом JSON."
authors = ["Azreil-OFD <fantom2413@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"