[build-system]
requires = ["hatchling","numpy==1.21.5","pandas==1.3.5"]
build-backend = "hatchling.build"

[project]
name = "pvai"
version = "0.0.2"
authors = [
  { name="Francis De Voogt", email="francisdevoogt@hotmail.com" },
]
description = "Data processing package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/pypa/sampleproject"
"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
