[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
[project]
name = "gandai"
version = "1.1.4"
authors = [
  { name="Parker Holcomb", email="parker.holcomb@gmail.com" },
]
description = "G&AI Research"
readme = "README.md"
requires-python = ">=3.9"

[tool.black]
line-length=88
target-version= ["py39"]

[tool.isort]
profile = "black"