[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AL_Khatma_lib"
version = "2.0.3"
authors = [
  { name="Osamah Awadh", email="osamahawadh01@gmail.com" },
]
description = "A library Specialized About Islamic"
readme = "README.md"
requires-python = ">=3"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/oaokm/AL-Khatma"
"Bug Tracker" = "https://github.com/oaokm/AL-Khatma/issues"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}