[tool.poetry]
name = "cave-sweeper"
version = "0.1.1"
description = ""
authors = ["Andr√© Lima"]
readme = "README.md"
packages = [{include = "cave_sweeper"}]

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
