[tool.poetry]
name = "tutorialleigos"
version = "0.1.3"
description = "Just a tutorial to test the behavior"
authors = ["Bruno SL"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.24.3"

[tool.poetry.scripts]
rodar-programa = "tutorialleigos.codigo:print_hello"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
